### ISSUE TITLE
Sidebar color not getting applied after updating to v217

### ISSUE THREAD

**Issue by reesion** [home-assistant-community-themes/material-dark-red#6]
Hi,

My sidebar color is not getting applied after updating to v217. Any idea how to fix?

![image](https://user-images.githubusercontent.com/53692597/79295754-d8b87300-7f1c-11ea-8534-90f921bf269b.png)

**Comment by maartenpaauw** [comment]
Hi @reesion! Recently I changed the template filename from `template.yaml` to `material_dark_red.yaml`. Can you make sure there is only `material_dark_red.yaml` within your `themes` folder and not the `template.yaml`.

**Comment by reesion** [comment]
That is the only file in the folder /config/themes/material_dark_red/material_dark_red.yaml

The content of the file is as follow

```
---
#
# Material Dark Red Theme
#
material_dark_red:
  dark-primary-color: "#c66900"
  disabled-text-color: "#545454"
  divider-color: "#333333"
  light-primary-color: "#e06c6c"
  paper-card-background-color: "#333333"
  paper-card-header-color: "var(--paper-item-icon-color)"
  paper-grey-200: "#191919"
  paper-grey-50: "var(--primary-text-color)"
  paper-item-icon-active-color: "var(--primary-color)"
  paper-item-icon-color: "#d3d3d3"
  paper-item-icon_-_color: "var(--paper-item-icon-color)"
  paper-listbox-background-color: "var(--paper-card-background-color)"
  paper-listbox-color: "var(--primary-text-color)"
  paper-slider-active-color: "var(--primary-color)"
  paper-slider-knob-color: "var(--primary-color)"
  paper-slider-knob-start-color: "var(--primary-color)"
  paper-slider-pin-color: "var(--primary-color)"
  paper-slider-secondary-color: "var(--light-primary-color)"
  paper-toggle-button-checked-bar-color: "var(--light-primary-color)"
  paper-toggle-button-checked-button-color: "var(--primary-color)"
  paper-toggle-button-checked-ink-color: "var(--dark-primary-color)"
  paper-toggle-button-unchecked-bar-color: "var(--primary-text-color)"
  primary-background-color: "#272822"
  primary-color: "#d32f2f"
  primary-text-color: "#cfcfcf"
  secondary-background-color: "#131313"
  secondary-text-color: "var(--primary-color)"
  sidebar-icon-color: "var(--paper-item-icon-color)"
  sidebar-text_-_background: "#333333"
  table-row-alternative-background-color: "var(--sidebar-text_-_background)"
  table-row-background-color: "var(--paper-card-background-color)"
```
